Add build instructions to README
MagmaWM/MagmaWM pull request #12
Opened 2023-05-15 18:20 UTC by hifinerd

Pretty self-explanatory. This adds instructions on how to build MagmaWM.

2023-05-15 18:23 UTC, HackedOS commented
Uhh the depends are not resolved by cargo, you also need to add instructions about setting up seatd properly

2023-05-15 18:25 UTC, hifinerd commented
> you also need to add instructions about setting up seatd properly
Is there any particular reference for that I should take a look at?

2023-05-15 18:31 UTC, HackedOS commented
You can look at the ci workflow file for the dependencies list (just translate them to dofferent distros)

2023-05-15 19:25 UTC, HackedOS commented
Please revert back to stable

2023-05-15 20:05 UTC, electron271 requested changes

2023-05-15 20:05 UTC, electron271 commented on README.md
>      <img src="https://cdn.discordapp.com/attachments/1090909610828898304/1101557907453120545/Magma_Concept_3__2.png" style="width: 15%;" alt="wmlogo"></img>
do not use discord's CDNs to be safe, use your own website

2023-05-15 20:05 UTC, electron271 commented on README.md
>      <img src="https://cdn.discordapp.com/attachments/1090909610828898304/1101557907453120545/Magma_Concept_3__2.png" style="width: 15%;" alt="wmlogo"></img>
also put the logo above the name

2023-05-15 20:05 UTC, electron271 commented on README.md
> +    <img src="https://img.shields.io/github/license/magmawm/magmawm?style=for-the-badge"/>
license is not really needed as a badge

2023-05-15 20:05 UTC, electron271 commented on README.md
>  **MagmaWM** is still under devlopment and can't be installed yet.
just at least put "If you really want to, run `cargo install --path .`"

2023-05-15 20:05 UTC, electron271 commented on README.md
> +
also suggest `cargo run --release`

2023-05-15 20:16 UTC, HackedOS commented
Add a section on how to report bugs that is, reading and sending logs etc, and add `cargo fmt` and `cargo clippy` to the contributing part

2023-05-15 21:05 UTC, HackedOS commented
Add dependency install commands for few pther distros mainly arch

2023-05-16 12:33 UTC, hifinerd commented
PR has been updated with the requested changes.

2023-05-16 12:35 UTC, HackedOS requested changes
Popups and RON config are added, add a section about cargo fmt and cargo clippy to contributing pls

2023-05-16 15:17 UTC, HackedOS commented
keyboard and monitor config is also completed

2023-05-16 15:19 UTC, Insert5StarName commented
> keyboard and monitor config is also completed

Full Keyboard Config?
layout etc?
Custom Remapping Caps to ctrl as an example?

2023-05-16 15:22 UTC, Insert5StarName commented
> > > keyboard and monitor config is also completed
> > 
> > 
> > Full Keyboard Config? layout etc? Custom Remapping Caps to ctrl as an example?
> 
> yes, @egreg10us has already tested aswell

Monitors are done too?
Binding Workspaces to Monitor?
etc?

2023-05-16 15:26 UTC, HackedOS commented
> > > > keyboard and monitor config is also completed
> > > 
> > > 
> > > Full Keyboard Config? layout etc? Custom Remapping Caps to ctrl as an example?
> > 
> > 
> > yes, @egreg10us has already tested aswell
> 
> Monitors are done too? Binding Workspaces to Monitor? etc?

only setting resolution and refresh rate done rn

2023-05-16 15:27 UTC, merged