add ipc to magma
MagmaWM/MagmaWM pull request #48
Opened 2023-06-01 02:06 UTC by electron271

i have re-appeared from the abyss ready to continue work

2023-06-01 02:07 UTC, electron271 commented
![merge-conflict](https://github.com/MagmaWM/MagmaWM/assets/66094410/c24b60f3-5a5b-490e-9379-7f4b57bd7625)

2023-06-01 22:17 UTC, a-weeb-programmer commented
Shouldn't the `src/ipc` dir be moved to `src/protocols/ipc` since it is a protocol manager?

2023-06-01 23:22 UTC, a-weeb-programmer commented
i resolved the merge conflict

2023-06-01 23:26 UTC, electron271 commented
> Shouldn't the `src/ipc` dir be moved to `src/protocols/ipc` since it is a protocol manager?

true



> i resolved the merge conflict

astrid W

2023-06-04 12:40 UTC, HackedOS requested changes
The whole thing is wrong, the ipc.xml and the wayland scanner needs to be in a standalone crate that can be used by any third party, then we need a wrapper crate thats the magmsg crate and yhen we have the main compositor itself

2023-06-04 17:56 UTC, electron271 commented
ipc.xml IS in its own crate, or am i just dumb
i have not worked with multi-crate projects in a few months

2023-06-04 18:01 UTC, HackedOS commented
> ipc.xml IS in its own crate, or am i just dumb i have not worked with multi-crate projects in a few months

There will be a total of 3 crates, one is the main comp, second is a library crate which provides wayland protocol bindings and the third is a client wrapper for the bindings

2025-05-07 22:43 UTC, closed without merging