Update udev.rs
MagmaWM/MagmaWM pull request #72
Opened 2024-02-15 17:55 UTC by twohexed

I think it would be better if we pass `true` in order to let the library manage the drm activation.

2024-02-15 18:08 UTC, electron271 requested changes
`backend.drm.activate` does not take arguments, as such this does not build

2024-02-15 18:12 UTC, twohexed commented
While compiling the same, the compilation aborted with an error saying that the `activate` function requires an argument of type bool. I’ll check again maybe there was a mistake from my end. Thanks.

2024-02-15 18:12 UTC, closed without merging

2024-02-15 18:23 UTC, electron271 commented
ill investigate later

2024-02-16 01:54 UTC, HackedOS commented
This was added in upstream about 1 month ago our dependencies are outdated, we would need to update the the dependencies to add this

2024-02-16 01:54 UTC, electron271 commented
yep my thoughts

i will run a update later

2024-02-16 01:55 UTC, HackedOS commented
> yep my thoughts
> 
> i will run a update later

Btw when updating test it throughly there have been some major changes recently alot of shit might be broken