made a github issues template
MagmaWM/MagmaWM pull request #95
Opened 2024-04-17 16:30 UTC by killertofus

2024-04-18 02:36 UTC, electron271 requested changes

2024-04-18 02:36 UTC, electron271 commented on .github/ISSUE_TEMPLATE /a_make_a_report.yml
> +        - label: I'm reporting a problem with Magmawm
should be MagmaWM

2024-04-18 02:36 UTC, electron271 commented on .github/ISSUE_TEMPLATE /a_make_a_report.yml
> +      placeholder: Magmawm 2.3.5 (commit 81a62764, 2022-04-05) on arch, kernel 6.8.1
2.3.5 doesnt exist and we didnt exist in 2022, best to replace with something like this:
```
MagmaWM git (commit 766d0d0)
```

2024-04-18 04:09 UTC, killertofus commented
fixed, thanks for the report

2024-04-18 17:01 UTC, electron271 requested changes

2024-04-18 17:01 UTC, electron271 commented on .github/ISSUE_TEMPLATE /config.yml
> +  - name: Issue about Magmawm
still has incorrect spelling

2024-04-18 17:11 UTC, killertofus commented
now it's fixed

2024-04-22 08:09 UTC, HackedOS requested changes

2024-04-22 08:09 UTC, HackedOS commented on .github/ISSUE_TEMPLATE/a_make_a_report.yml
> +        - label: I've looked for my problem on the [wiki](https://github.com/MagmaWM/MagmaWM/Help/)
the correct link for the docs/wiki https://magmawm.org/docs/

2024-04-22 08:09 UTC, HackedOS commented on .github/ISSUE_TEMPLATE/a_make_a_report.yml
> +        - label: I've searched the [issues and pull requests](https://github.com/MagmaWM/MagmaWM/issues?q=) for similar looking reports
why the trailing ?q=

2024-04-22 08:09 UTC, HackedOS commented on pkgbuild/PKGBUILD
why is there a pkgbuild we dont intend to add one till release

2024-04-22 08:09 UTC, HackedOS commented on .github/ISSUE_TEMPLATE/a_make_a_report.yml
we want a section about a how to send logs and send WAYLAND_DEBUG logs for specific software they are having issues with

2024-10-12 23:41 UTC, closed without merging